apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pea-cron-test
  namespace: pea
spec:
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: safe-plateau
            image: appropriate/curl:latest
            command: ["curl"]
            args: ["-s", "https://safe-plateau-51528.herokuapp.com/documentation"]
            