apiVersion: v1
kind: Namespace 
metadata:
  name: pea

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: pea
spec:
  backend:
    serviceName: pea-service
    servicePort: 9000

---

kind: Service
apiVersion: v1
metadata:
  name: pea-service
  namespace: pea 
spec:
  type: NodePort
  selector:
    app: pea
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pea
  namespace: pea
  labels:
    app: pea
    veg: pea 
    type: vegetable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pea
  template:
    metadata:
      labels:
        app: pea
    spec:
      containers:
        - name: pea
          image: rafaelmarques7/pea-app:v6
          imagePullPolicy: Always
          ports:
            - name: pea-port
              containerPort: 9000
              protocol: TCP
          env:
          - name: MY_NAME
            value: "samuel"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000
              httpHeaders:
              - name: X-Custom-Header
                value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3
